import { IRegister } from 'types/register';

export const StudentForm: IRegister = {
  id: 1,
  name: 'Datos del Alumno',
  questions: [
    {
      id: 1,
      question: 'CURP',
      name: 'curp',
      required: false,
      editable: true,
      type: 'input',
    },
    {
      id: 2,
      question: 'Nombre',
      name: 'name',
      editable: true,
      required: true,
      type: 'input',
    },
    {
      id: 3,
      question: 'Primer Apellido',
      name: 'first_lastname',
      required: true,
      editable: false,
      type: 'input',
    },
    {
      id: 4,
      question: 'Segundo Apellido (Opcional)',
      name: 'second_lastname',
      required: false,
      editable: false,
      type: 'input',
    },
    {
      id: 5,
      question: 'Grado',
      name: 'year',
      required: true,
      editable: true,
      type: 'select',
      option: ['1', '2', '3'].map((option) => ({
        label: option,
        value: option,
      })),
    },
    {
      id: 6,
      question: 'Turno',
      name: 'schedule',
      required: true,
      editable: true,
      type: 'select',
      option: ['MATUTINO', 'VESPERTINO'].map((option) => ({
        label: option,
        value: option,
      })),
    },
    {
      id: 7,
      question: 'Clave del plantel',
      name: 'cct',
      required: true,
      editable: true,
      type: 'select',
      option: [],
    },
    {
      id: 8,
      question: 'Plantel',
      name: 'school',
      required: true,
      editable: true,
      type: 'select',
      option: [],
      disable: true,
    },
    {
      id: 9,
      question: 'Subsistema',
      name: 'subsystem',
      required: true,
      editable: true,
      type: 'select',
      option: [],
      disable: true,
    },
  ],
};
